---
media_downloads_dir: "{{ storage_smb_share_local_dir }}/Downloads"
media_movies_dir: "{{ storage_smb_share_local_dir }}/Movies"
media_tvseries_dir: "{{ storage_smb_share_local_dir }}/TV"
media_photos_dir: "{{ storage_smb_share_local_dir }}/Photos"

# https://hub.docker.com/r/linuxserver/transmission/tags
media_transmission_version: "latest"
media_transmission_ui_port: 9091
media_transmission_peer_port: 10411
media_transmission_whitelist:
  - "127.0.0.1"
  - "172.23.0.*" # docker network
  - "192.168.2.*" # lan
  - "10.8.*.*" # vpn network

# https://hub.docker.com/r/linuxserver/radarr/tags
media_radarr_version: "latest"
media_radarr_port: 7878

# https://hub.docker.com/r/linuxserver/sonarr/tags
media_sonarr_version: "latest"
media_sonarr_port: 8989

# https://hub.docker.com/r/linuxserver/prowlarr/tags
media_prowlarr_version: "latest"
media_prowlarr_port: 9696

# https://hub.docker.com/r/linuxserver/jellyfin/tags
media_jellyfin_version: "latest"
media_jellyfin_port: 8096
media_jellyfin_discovery_port: 7359

# https://hub.docker.com/r/fallenbagel/jellyseerr/tags
media_jellyseerr_version: "latest"
media_jellyseerr_port: 5055

# https://github.com/immich-app/immich/pkgs/container/immich-server/versions?filters%5Bversion_type%5D=tagged
media_immich_version: "release"
media_immich_port: 3001
