---
- hosts: "all"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "docker"
      tags:
        - "docker"

    - role: "fail2ban"
      tags:
        - "fail2ban"
      when: |
        fail2ban_service_enabled

    - role: "ufw"
      tags:
        - "ufw"
      when: |
        ufw_service_enabled

    - role: "ssh"
      tags:
        - "ssh"
      when: |
        ssh_service_enabled

    - role: "wireguard"
      tags:
        - "wireguard"
      when: |
        wireguard_service_enabled

    - role: "authelia"
      tags:
        - "authelia"
      when: |
        authelia_service_enabled

    - role: "bunkerweb"
      tags:
        - "bunkerweb"
      when: |
        bunkerweb_service_enabled

    - role: "gitea"
      tags:
        - "gitea"
      when: |
        gitea_service_enabled

    - role: "fireflyiii"
      tags:
        - "fireflyiii"
      when: |
        fireflyiii_service_enabled

    - role: "rssbridge"
      tags:
        - "rssbridge"
      when: |
        rssbridge_service_enabled

    - role: "freshrss"
      tags:
        - "freshrss"
      when: |
        freshrss_service_enabled

    - role: "sonarr"
      tags:
        - "sonarr"
      when: |
        sonarr_service_enabled
