---
- name: "Provision github_ci host"
  hosts: "github_ci"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "artyorsh.selfhosted.docker"
      tags:
        - "docker"

    - role: "monitoring"
      tags:
        - "monitoring"

    - role: "artyorsh.yams.yams"
      tags:
        - "media"

    - role: "artyorsh.smarthome.smarthome"
      tags:
        - "smarthome"

    - role: "artyorsh.selfhosted.rss"
      tags:
        - "rss"

    - role: "artyorsh.selfhosted.homebox"
      tags:
        - "homebox"

    - role: "artyorsh.selfhosted.vaultwarden"
      tags:
        - "vaultwarden"

    - role: "artyorsh.selfhosted.duplicati"
      tags:
        - "duplicati"

    - role: "artyorsh.selfhosted.watchtower"
      tags:
        - "watchtower"

    - role: "artyorsh.selfhosted.wallos"
      tags:
        - "wallos"

    - role: "artyorsh.selfhosted.nginx"
      tags:
        - "nginx"

    - role: "wireguard"
      tags:
        - "wireguard"

    - role: "artyorsh.selfhosted.authelia"
      tags:
        - "authelia"
