---
- hosts: "medialab"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "security"
      tags:
        - "security"

    - role: "docker"
      tags:
        - "docker"

    - role: "cloudflare"
      tags:
        - "cloudflare"

    - role: "wireguard"
      tags:
        - "wireguard"

    - role: "dashboard"
      tags:
        - "dashboard"

    - role: "media"
      tags:
        - "media"
