---
- name: "Provision pi host"
  hosts: "pi"
  become: true

  pre_tasks:
    - ansible.builtin.import_tasks: "tasks/docker-registry-login.yml"
      tags:
        - "docker"
        - "always"

    - ansible.builtin.import_tasks: "tasks/mount-smb-share.yml"
      vars:
        src: "{{ smb_share_base_url }}"
        path: "{{ smb_share_local_dir }}"
      tags:
        - "media"
        - "duplicati"

    - ansible.builtin.import_tasks: "tasks/mount-smb-share.yml"
      vars:
        src: "{{ smb_share_base_url }}/repositories"
        path: "{{ forgejo_repositories_dir }}"
      tags:
        - "smb"
        - "forgejo"

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "docker"
      tags:
        - "docker"

    - role: "wireguard"
      tags:
        - "wireguard"

    - role: "artyorsh.jellyfin"
      tags:
        - "jellyfin"
        - "media"

    - role: "artyorsh.immich"
      tags:
        - "immich"

    - role: "artyorsh.nginx"
      tags:
        - "nginx"

    - role: "artyorsh.openarchiver"
      tags:
        - "openarchiver"

    - role: "artyorsh.paperlessngx"
      tags:
        - "paperlessngx"

    - role: "smarthome"
      tags:
        - "smarthome"
        - "homeassistant"
        - "mosquitto"
        - "zigbee2mqtt"

    - role: "artyorsh.miniflux"
      tags:
        - "miniflux"
        - "rss"

    - role: "artyorsh.syncthing"
      tags:
        - "syncthing"

    - role: "artyorsh.homebox"
      tags:
        - "homebox"

    - role: "artyorsh.vaultwarden"
      tags:
        - "vaultwarden"

    - role: "artyorsh.duplicati"
      tags:
        - "duplicati"

    - role: "artyorsh.wallos"
      tags:
        - "wallos"

    - role: "artyorsh.forgejo"
      tags:
        - "forgejo"

    - role: "artyorsh.dnsmasq"
      tags:
        - "dnsmasq"

    - role: "website"
      tags:
        - "website"
