---
- name: "Provision pi host"
  hosts: "pi"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "artyorsh.selfhosted.docker"
      tags:
        - "docker"

    - role: "artyorsh.selfhosted.adguardhome"
      tags:
        - "adguardhome"

    - role: "wireguard"
      vars:
        wireguard_mode: "client"
      tags:
        - "wireguard"

    - role: "storage"
      tags:
        - "storage"

    - role: "artyorsh.yams.yams"
      tags:
        - "media"

    - role: "artyorsh.smarthome.smarthome"
      tags:
        - "smarthome"

    - role: "monitoring"
      tags:
        - "monitoring"

    - role: "artyorsh.selfhosted.rss"
      tags:
        - "rss"

    - role: "artyorsh.selfhosted.homebox"
      tags:
        - "homebox"

    - role: "artyorsh.selfhosted.vaultwarden"
      tags:
        - "vaultwarden"

    - role: "artyorsh.selfhosted.duplicati"
      tags:
        - "duplicati"

    - role: "artyorsh.selfhosted.watchtower"
      tags:
        - "watchtower"

    - role: "artyorsh.selfhosted.wallos"
      tags:
        - "wallos"

    - role: "artyorsh.selfhosted.authelia"
      vars:
        authelia_version: "4.38.9"
      tags:
        - "authelia"

    - role: "artyorsh.selfhosted.cloudflare"
      tags:
        - "cloudflare"
