---
- name: "Provision mac host"
  hosts: "mac"

  roles:
    - role: "elliotweiser.osx-command-line-tools"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "dotfiles"
      tags:
        - "dotfiles"

    - role: "homebrew"
      tags:
        - "homebrew"

  tasks:
    - name: "Configure mobile dev environment"
      ansible.builtin.include_role:
        name: "artyorsh.mobiledev.rn"
      vars:
        rn_shell_paths_file: "$HOME/.zprofile"
