---
- name: "Provision pi host"
  hosts: "pi"
  become: true

  pre_tasks:
    - ansible.builtin.import_tasks: "tasks/docker-registry-login.yml"
      tags:
        - "docker"

    - ansible.builtin.import_tasks: "tasks/mount-smb-share.yml"
      vars:
        src: "{{ smb_share_base_url }}"
        path: "{{ smb_share_local_dir }}"
      tags:
        - "media"
        - "duplicati"

    - ansible.builtin.import_tasks: "tasks/mount-smb-share.yml"
      vars:
        src: "{{ smb_share_base_url }}/repositories"
        path: "{{ forgejo_repositories_dir }}"
      tags:
        - "forgejo"

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "artyorsh.selfhosted.docker"
      tags:
        - "docker"

    - role: "wireguard"
      vars:
        wireguard_mode: "client"
      tags:
        - "wireguard"

    - role: "artyorsh.yams.yams"
      tags:
        - "media"

    - role: "monitoring"
      tags:
        - "monitoring"

    - role: "artyorsh.selfhosted.paperlessngx"
      tags:
        - "paperlessngx"

    - role: "artyorsh.selfhosted.paperless_ai"
      tags:
        - "paperlessngx"
        - "paperless-ai"

    - role: "artyorsh.selfhosted.postiz"
      tags:
        - "postiz"

    - role: "artyorsh.smarthome.smarthome"
      vars:
        smarthome_zigbee_adapter: "/dev/ttyUSB0"
      tags:
        - "smarthome"

    - role: "artyorsh.selfhosted.rss"
      tags:
        - "rss"

    - role: "artyorsh.selfhosted.homebox"
      tags:
        - "homebox"

    - role: "artyorsh.selfhosted.vaultwarden"
      tags:
        - "vaultwarden"

    - role: "artyorsh.selfhosted.duplicati"
      tags:
        - "duplicati"

    - role: "artyorsh.selfhosted.watchtower"
      tags:
        - "watchtower"

    - role: "artyorsh.selfhosted.wallos"
      tags:
        - "wallos"

    - role: "artyorsh.selfhosted.forgejo"
      tags:
        - "forgejo"

    - role: "website"
      tags:
        - "website"
