---
- name: "Provision pi host"
  hosts: "pi"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "docker"
      tags:
        - "docker"

    - role: "artyorsh.selfhosted.cloudflare"
      tags:
        - "cloudflare"

    - role: "wireguard"
      tags:
        - "wireguard"

    - role: "storage"
      tags:
        - "storage"

    - role: "media"
      tags:
        - "media"

    - role: "smarthome"
      tags:
        - "smarthome"

    - role: "artyorsh.selfhosted.glances"
      vars:
        glances_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "glances"

    - role: "artyorsh.selfhosted.homarr"
      vars:
        homarr_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "homarr"

    - role: "artyorsh.selfhosted.freshrss"
      vars:
        freshrss_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "freshrss"

    - role: "artyorsh.selfhosted.paperlessngx"
      vars:
        paperlessngx_consume_dir: "{{ storage_smb_share_local_dir }}/Documents/inbox"
        paperlessngx_media_dir: "{{ storage_smb_share_local_dir }}/Documents"
        paperlessngx_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "paperlessngx"

    - role: "artyorsh.selfhosted.vaultwarden"
      vars:
        vaultwarden_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "vaultwarden"

    - role: "artyorsh.selfhosted.duplicati"
      vars:
        duplicati_source_dir: "{{ storage_smb_share_local_dir }}"
        duplicati_backups_dir: "{{ storage_smb_share_local_dir }}/backups"
        duplicati_docker_settings: "{{ docker_default_settings }}"
      tags:
        - "duplicati"
