---
- name: "Provision vps host"
  hosts: "vps"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "artyorsh.selfhosted.docker"
      tags:
        - "docker"

    - role: "artyorsh.selfhosted.headscale"
      tags:
        - "headscale"

    - role: "tailscale"
      tags:
        - "tailscale"

  tasks:
    - ansible.builtin.import_tasks: "tasks/scheduled-reboot.yml"
      tags:
        - "reboot"
