---
- name: "Provision vps host"
  hosts: "vps"
  become: true

  roles:
    - role: "system"
      tags:
        - "system"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "security"
      tags:
        - "security"

    - role: "docker"
      tags:
        - "docker"

    - role: "cloudflare"
      tags:
        - "cloudflare"

    - role: "wireguard"
      tags:
        - "wireguard"
