---
- name: "Mac"
  hosts: "mac"

  roles:
    - role: "elliotweiser.osx-command-line-tools"

    - role: "zsh"
      tags:
        - "zsh"

    - role: "dotfiles"
      tags:
        - "dotfiles"

    - role: "homebrew"
      tags:
        - "homebrew"
