---
roles:
  - name: "geerlingguy.docker"
    src: "https://github.com/geerlingguy/ansible-role-docker"

  - name: "geerlingguy.security"
    src: "https://github.com/geerlingguy/ansible-role-security"

  - name: "elliotweiser.osx-command-line-tools"

  - name: "homeassistant"
    src: "https://forgejo.artyorsh.me/artyorsh/ansible-role-homeassistant"
    scm: "git"
    version: "v1.0.0"

  - name: "mosquitto"
    src: "https://forgejo.artyorsh.me/artyorsh/ansible-role-mosquitto"
    scm: "git"
    version: "v1.0.0"

  - name: "zigbee2mqtt"
    src: "https://forgejo.artyorsh.me/artyorsh/ansible-role-zigbee2mqtt"
    scm: "git"
    version: "v1.0.0"

collections:
  - name: "https://github.com/ansible-collections/community.general"
    type: "git"

  - name: "https://github.com/ansible-collections/ansible.posix"
    type: "git"

  - name: "https://github.com/artyorsh/ansible-collection-yams"
    type: "git"

  - name: "https://github.com/artyorsh/ansible-collection-mobiledev"
    type: "git"

  - name: "artyorsh.selfhosted"

  - name: "geerlingguy.mac"
