#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  vars_files:
    - secret.yml

  pre_tasks:
    - name: Check if inside AWS.
      uri:
        url: http://169.254.169.254/latest/meta-data/ami-id
        timeout: 2
      register: aws_uri_check
      failed_when: False

    - set_fact:
        aws: "{{ aws_uri_check.status == 200 }}"

  roles:
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    - role: fail2ban
      when: enable_fail2ban | default(False)
      tags:
        - fail2ban

    - role: ufw
      when: enable_ufw | default(False)
      tags:
        - ufw

    - role: authelia
      tags:
        - authelia

    - role: bunkerweb
      tags:
        - bunkerweb

    - role: wireguard
      tags:
        - wireguard

    - role: chriswayg.msmtp-mailer
      when: email_password is defined
      tags:
        - msmtp

    - role: ssh
      tags:
        - ssh
