name: "Run playbook"

inputs:
  tags:
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        ansible-playbook playbook-github-ci.yml \
        --vault-password-file vault.ci.sh \
        --tags ${{ inputs.tags }} \
        -v
      shell: "bash"
