---
- block:
  - name: "Ensure UFW is not installed"
    ansible.builtin.command: "service ufw status"
      register: ufw_installed
      ignore_errors: true
      changed_when: false
      check_mode: false

  - name: "Stop UFW (when not installed)"
    ansible.builtin.service:
      name: "ufw"
      state: "stopped"
      enabled: false
    when: ufw_installed.rc == 0

- name: "Define ipv4 interface for Docker"
  block:
    - ansible.builtin.set_fact:
        security_iptables_docker_interface: "{{ ansible_default_ipv4.interface }}"
      when: wg_host_mode_enabled
    - ansible.builtin.set_fact:
        security_iptables_docker_interface: "ens33"
      when: wg_client_mode_enabled

- name: "Template iptables rules"
  ansible.builtin.template:
    src: "iptables.conf"
    dest: "/etc/iptables.conf"
    owner: "root"
    group: "root"
    mode: "0744"

- name: "Copy iptables systemd service"
  ansible.builtin.copy:
    src: "files/iptables.service"
    dest: "/etc/systemd/system/iptables.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Enable and start iptables service"
  ansible.builtin.service:
    name: "iptables"
    state: "started"
    enabled: true
