---
- name: "Configure SSH"
  ansible.builtin.include_tasks: "ssh.yml"

# See https://github.com/geerlingguy/ansible-role-security
- name: "Run geerlingguy.security role"
  ansible.builtin.include_role:
    name: "geerlingguy.security"
  vars:
    security_ssh_allowed_users: ["{{ system_user.name }}"]
    security_sudoers_passwordless: ["{{ system_user.name }}"]

- name: "Uninstall UFW"
  ansible.builtin.include_tasks: "uninstall-ufw.yml"

- name: "Configure iptables"
  ansible.builtin.include_tasks: "iptables.yml"
