---
- name: "Configure SSH"
  ansible.builtin.include_tasks: "ssh.yml"

- name: "Run geerlingguy.security role"
  ansible.builtin.include_role:
    name: "geerlingguy.security"

- name: "Uninstall UFW"
  ansible.builtin.include_tasks: "uninstall-ufw.yml"

- name: "Configure iptables"
  ansible.builtin.include_tasks: "iptables.yml"
