---
# https://github.com/linuxserver/docker-homeassistant#parameters
#
# Bluetooth:
# https://docs.linuxserver.io/images/docker-homeassistant/#accessing-bluetooth-device
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-capabilities
#
# HomeKit: https://www.home-assistant.io/integrations/homekit/

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    homeassistant_service_id: "homeassistant"
    homeassistant_root_dir: "{{ docker_dir }}/homeassistant"

- name: "Create service directories"
  ansible.builtin.file:
    path: "{{ homeassistant_root_dir }}"
    state: "directory"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_group }}"
    mode: "0770"

- name: "Permit cloudflare access"
  block:
    - name: "Get cloudflare container info"
      community.docker.docker_container_info:
        name: "cloudflare"
      register: cloudflare_container_info

    - name: "Set cloudflare container IP in trusted proxies"
      ansible.builtin.set_fact:
        home_homeassistant_trusted_proxies:
          - desc: "cloudflare@{{ home_network_name }}"
            address: "{{ cloudflare_container_info.container.NetworkSettings.Networks[home_network_name].IPAddress }}"

- name: "Template configuration.yml"
  ansible.builtin.template:
    src: "ha-configuration.yaml.j2"
    dest: "{{ homeassistant_root_dir }}/configuration.yaml"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_group }}"
    mode: "0644"

- name: "Run homeassistant container"
  community.general.docker_container:
    name: "{{ homeassistant_service_id }}"
    image: "lscr.io/linuxserver/homeassistant:{{ home_homeassistant_version }}"
    networks:
      - name: "{{ home_network_name }}"
    state: "started"
    env:
      TZ: "{{ system_timezone }}"
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
    ports:
      - "{{ home_homeassistant_port }}:8123"
    volumes:
      - "{{ homeassistant_root_dir }}:/config"
    restart_policy: "unless-stopped"
