# https://www.zigbee2mqtt.io/guide/installation/02_docker.html
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-devices
---
- ansible.builtin.set_fact:
    zigbee2mqtt_service_id: "zigbee2mqtt"
    zigbee2mqtt_root_dir: "{{ docker_dir }}/zigbee2mqtt"

- name: "Create service directories"
  ansible.builtin.file:
    path: "{{ zigbee2mqtt_root_dir }}"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0770"

- name: "Register {{ mosquitto_service_id }} ip address"
  block:
    - community.docker.docker_container_info:
        name: "{{ mosquitto_service_id }}"
      register: mosquitto_container_info

    - ansible.builtin.set_fact:
        home_zigbee2mqtt_broker_address: "{{ mosquitto_container_info.container.NetworkSettings.Networks[home_network_name].IPAddress }}"

- name: "Template configuration.yml"
  ansible.builtin.template:
    src: "zigbee2mqtt-configuration.yaml.j2"
    dest: "{{ zigbee2mqtt_root_dir }}/configuration.yaml"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: "Run zigbee2mqtt container"
  community.general.docker_container:
    name: "{{ zigbee2mqtt_service_id }}"
    image: "koenkk/zigbee2mqtt:{{ home_zigbee2mqtt_version }}"
    networks:
      - name: "{{ home_network_name }}"
    state: "started"
    env:
      TZ: "{{ system_timezone }}"
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
    groups:
      - "dialout"
    devices:
      - "{{ home_zigbee2mqtt_device }}:/dev/ttyACM0"
    ports:
      - "{{ home_zigbee2mqtt_port }}:8080"
    volumes:
      - "{{ zigbee2mqtt_root_dir }}:/app/data"
    restart_policy: "unless-stopped"
