---
- name: "Create smarthome network"
  community.general.docker_network:
    name: "{{ smarthome_network_name }}"

- name: "Bootstrap smarthome server"
  ansible.builtin.include_role:
    name: "artyorsh.smarthome.smarthome"
  vars:
    smarthome_user:
      name: "{{ system_user_name }}"
      password: "{{ system_user_password }}"

    smarthome_zigbee_coordinator: "/dev/ttyUSB0"

    smarthome_docker_settings:
      network: "{{ smarthome_network_name }}"
      puid: "{{ system_user_uid }}"
      pgid: "{{ system_user_gid }}"
      tz: "{{ system_timezone }}"
