---
- name: "Generate secrets if not defined"
  block:
    - ansible.builtin.assert:
        that:
          - authelia_jwt_secret is defined
          - authelia_session_secret is defined
          - authelia_encryption_key is defined
        fail_msg: "Secret variables are not defined. Will generate to continue"
      register: assert_secrets
      ignore_errors: true

    - ansible.builtin.set_fact:
        authelia_jwt_secret: "{{ lookup('community.general.random_string', length=20, special=false) }}"
        authelia_session_secret: "{{ lookup('community.general.random_string', length=20, special=false) }}"
        authelia_encryption_key: "{{ lookup('community.general.random_string', length=20, special=false) }}"
      when: assert_secrets.failed
