---
- ansible.builtin.include_tasks: "assertions.yml"

- name: "Create config folder"
  ansible.builtin.file:
    path: "{{ docker_dir }}/authelia"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: "Copy config files"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ docker_dir }}/authelia/{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
  with_items:
    - src: "authelia_config.yml.j2"
      dest: "configuration.yml"
    - src: "authelia_users.yml.j2"
      dest: "users_database.yml"
  notify: Restart authelia

- name: "Make sure Redis container is created and running"
  community.general.docker_container:
    name: "redis"
    image: "redis:alpine"
    networks:
      - name: "{{ docker_network_name }}"
    pull: true
    state: "started"
    restart_policy: "unless-stopped"

- name: "Make sure Authelia container is created and running"
  community.general.docker_container:
    name: "authelia"
    image: "authelia/authelia:latest"
    networks:
      - name: "{{ docker_network_name }}"
    pull: true
    state: "started"
    volumes:
      - "{{ docker_dir }}/authelia:/config"
    # ports:
    #   - "{{ authelia_port }}:9091"
    restart_policy: "unless-stopped"
