---
- name: "Create config folders"
  ansible.builtin.file:
    path: "{{ docker_dir }}/bunkerweb/data"
    state: "directory"
    owner: "{{ user_name }}"
    group: 101
    mode: 0770
  loop:
    - bunkerweb/
    - bunkerweb/data

- name: "Copy env file"
  ansible.builtin.template:
    src: "bunkerweb.env.j2"
    owner: "{{ user_name }}"
    group: 101
    mode: 0664
    dest: "{{ docker_dir }}/bunkerweb/.env"

- name: "Make sure Bunkerweb container is created and running"
  community.general.docker_container:
    name: "bunkerweb"
    image: "bunkerity/bunkerweb:{{ bunkerweb_version }}"
    networks:
      - name: "{{ docker_network_name }}"
    pull: true
    state: "started"
    env_file: "{{ docker_dir }}/bunkerweb/.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ docker_dir }}/bunkerweb/data:/data"
      - "/lib/modules:/lib/modules"
    restart_policy: "unless-stopped"
