---
- name: "Install cryptography"
  pip:
    name: "cryptography"
    state: "latest"

- name: "Create the SSH directory"
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700

- name: "Install the existing public key"
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ ssh_public_key }}"

- name: "Update SSH configuration to be more secure"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "present"
    validate: "sshd -T -f %s"
    mode: 0644
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?Port"
      line: "Port {{ ssh_port }}"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"
  notify: "Restart sshd daemon"

- name: "Schedule a reboot if required"
  stat:
    path: "/var/run/reboot-required"
  register: "reboot_required"

- name: "Reboot the system if updates are pending"
  when: "reboot_required.stat.exists"
  command:
    cmd: "reboot"
