---

- name: Install cryptography
  pip:
    name: cryptography
    state: latest

- name: Create the SSH directory
  file:
    path: "/home/{{ system_user }}/.ssh"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0700

- name: Install the existing public key
  authorized_key:
    user: "{{ system_user }}"
    key: "{{ ssh_public_key }}"

- name: Update SSH configuration to be more secure
  register: ssh_config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -T -f %s"
    mode: 0644
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?Port"
      line: "Port {{ ssh_port }}"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"

- name: Restart sshd daemon
  when: ssh_config.changed
  service:
    name: sshd
    state: restarted

- name: Schedule a reboot if required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the system if updates are pending
  when: reboot_required.stat.exists
  command:
    cmd: reboot