---
- name: "Configure locale"
  community.general.locale_gen:
    name: "{{ system_locale }}"
    state: "present"

- name: "Configure timezone"
  community.general.timezone:
    name: "{{ system_timezone }}"
