---

- name: Ensure group sudo exists
  group:
    name: sudo
    state: present

- name: Allow sudo group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create a login user
  user:
    name: "{{ system_user }}"
    password: "{{ system_user_password | string | password_hash('sha512') }}"
    groups:
      - sudo
      - users
    state: present
    append: true
    shell: "{{ shell }}"

- name: Ensure group "{{ system_user }}" exists
  group:
    name: "{{ system_user }}"
    state: present

- name: Chmod the user home directory
  file:
    path: "/home/{{ system_user }}"
    state: directory
    mode: 0755
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: true