---
- name: "Create a login user"
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password | string | password_hash('sha512') }}"
    groups:
      - "sudo"
      - "users"
    state: "present"
    append: true

- name: "Ensure group {{ user_name }} exists"
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: "present"

- name: "Chmod the user home directory"
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    state: "directory"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: true
