---
- name: "Template notification script"
  ansible.builtin.template:
    src: "notify.sh.j2"
    dest: "/opt/docker/glances/notify.sh"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_group }}"
    mode: "0740"

- name: "Install and configure Glances"
  ansible.builtin.include_role:
    name: "artyorsh.selfhosted.glances"
  vars:
    glances_notifier: "/opt/docker/glances/notify.sh"
    glances_fs_volumes:
      - "{{ storage_smb_share_local_dir }}"
    glances_docker_settings:
      network: "host"
      puid: "host"
      pgid: "{{ system_user_gid }}"
      tz: "{{ system_timezone }}"
  tags:
    - "glances"
