---
- name: "Template notification script"
  ansible.builtin.template:
    src: "notify.sh.j2"
    dest: "/etc/glances-notify.sh"
    owner: "{{ system_user.name }}"
    group: "{{ system_user.group }}"
    mode: "0740"

- name: "Install and configure Glances"
  ansible.builtin.include_role:
    name: "artyorsh.selfhosted.glances"

- name: "Install and configure OliveTin"
  ansible.builtin.include_tasks: "olivetin.yml"
