# Config: https://raw.githubusercontent.com/OliveTin/OliveTin/main/config.yaml
# Icons: get the unicode from https://emojipedia.org/

- name: "Install and configure OliveTin"
  ansible.builtin.include_role:
    name: "artyorsh.selfhosted.olivetin"
  vars:
    olivetin_docker_settings: "{{ docker_host_network_settings }}"
    olivetin_config:
      actions:
        - title: "Check ip address"
          icon: "🌐"
          shell: "curl api.ipify.org"
          popupOnStart: "execution-dialog-stdout-only"

        - title: "Restart Docker Container"
          icon: "🔄"
          shell: "{% raw %}docker restart {{ container }}{% endraw %}"
          timeout: 20
          arguments:
            - name: "container"
              title: "Container Name"
              choices:
                - value: "jellyfin jellyseerr"
                - value: "immich-db immich immich-microservices immich-machine-learning"
                - value: "miniflux-db rssbridge miniflux"
                - value: "mosquitto zigbee2mqtt homeassistant"
                - value: "paperlessngx-redis paperlessngx"
                - value: "transmission radarr sonarr prowlarr searcharr"
