---
- name: "Install ZSH (if not macos)"
  ansible.builtin.include_tasks: "zsh.yml"
  when: ansible_distribution != "MacOSX"

- name: "Install OhMyZSH"
  ansible.builtin.include_tasks: "omz.yml"

- name: "Install OhMyZSH plugins"
  ansible.builtin.include_tasks: "omz-plugins.yml"
