---
- name: "Check if Oh My ZSH is installed"
  ansible.builtin.stat:
    path: "$HOME/.oh-my-zsh"
  register: zsh_ohmyzsh_installed

- name: "Download installer"
  when: not zsh_ohmyzsh_installed.stat.exists
  ansible.builtin.get_url:
    url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/install-ohmyzsh.sh"
    mode: "0755"

- name: "Install Oh My ZSH"
  when: not zsh_ohmyzsh_installed.stat.exists
  ansible.builtin.command: "/tmp/install-ohmyzsh.sh --unattended"
  changed_when: not zsh_ohmyzsh_installed.stat.exists
