---
- name: "Create docker directories"
  file:
    path: "{{ gitea_docker_dir }}/{{ item }}"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "data"

- name: "Copy env file"
  template:
    src: "gitea.env.j2"
    dest: "{{ gitea_docker_dir }}/.env"
    mode: 0644

- name: "Run Gitea container"
  docker_container:
    name: "{{ gitea_service_id }}"
    image: "gitea/gitea:latest"
    pull: true
    networks:
      - name: "{{ wireguard_service_id }}"
      - name: "{{ gitea_service_id }}"
    state: "started"
    env_file: "{{ gitea_docker_dir }}/.env"
    ports:
      - "{{ gitea_port }}:3000"
      - "222:{{ ssh_port }}"
    volumes:
      - "{{ gitea_docker_dir }}/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: "unless-stopped"
