---
- name: "Restart authelia"
  community.general.docker_container:
    name: "authelia"
    restart: true

- name: "Restart bunkerweb"
  community.general.docker_container:
    name: "bunkerweb"
    restart: yes