---
# https://github.com/linuxserver/docker-prowlarr#docker-compose-recommended-click-here-for-more-info

- name: "Create docker directories"
  file:
    path: "{{ prowlarr_docker_dir }}"
    state: "directory"
    owner: "www-data"
    group: "www-data"
    mode: 0770

- name: "Run app container"
  docker_container:
    name: "{{ prowlarr_service_id }}"
    image: "linuxserver/prowlarr:{{ prowlarr_image_channel }}"
    pull: true
    networks:
      - name: "{{ wireguard_service_id }}"
      - name: "{{ prowlarr_service_id }}"
    state: "started"
    env:
      TZ: "{{ system_timezone }}"
    ports:
      - "{{ prowlarr_port }}:80"
    volumes:
      - "{{ prowlarr_docker_dir }}:/config"
    restart_policy: "unless-stopped"
