---
ansible_user: "runner_42"

system_user:
  name: "{{ ansible_user }}"
  password: "changeme"
  group: "{{ ansible_user }}"
  uid: "4242"
  gid: "4242"

system_timezone: "Europe/Amsterdam"

#################################
# docker                        #
#################################

docker_bridge_network_settings:
  network: "docker-network-main"
  puid: "{{ system_user.uid }}"
  pgid: "{{ system_user.gid }}"
  tz: "{{ system_timezone }}"

docker_host_network_settings:
  network: "host"
  puid: "host"
  pgid: "{{ system_user.gid }}"
  tz: "{{ system_timezone }}"

#################################
# ansilbe-collection-yams       #
#################################

yams_docker_settings: "{{ docker_bridge_network_settings }}"
yams_user: "{{ system_user }}"

immich_port: 3001

jellyfin_port: 3002
jellyfin_jellyseerr_port: 3003

paperlessngx_port: 3004

prowlarr_port: 3005

radarr_port: 3006

sonarr_port: 3007

transmission_ui_port: 3008
transmission_whitelist:
  - "*.*.*.*"

#################################
# ansilbe-collection-selfhosted #
#################################

authelia_docker_settings: "{{ docker_bridge_network_settings }}"
authelia_port: 3019

duplicati_docker_settings: "{{ docker_bridge_network_settings }}"
duplicati_port: 3009

forgejo_docker_settings: "{{ docker_bridge_network_settings }}"
forgejo_webui_port: 3010

glances_docker_settings: "{{ docker_host_network_settings }}"
glances_webui_port: 61208

homebox_docker_settings: "{{ docker_bridge_network_settings }}"
homebox_webui_port: 3011

nginx_docker_settings: "{{ docker_bridge_network_settings }}"
nginx_port_admin: 3018

rss_docker_settings: "{{ docker_bridge_network_settings }}"
rss_miniflux_webui_port: 3012
rss_rssbridge_webui_port: 3013

vaultwarden_docker_settings: "{{ docker_bridge_network_settings }}"
vaultwarden_port: 3014

watchtower_docker_settings: "{{ docker_bridge_network_settings }}"

wallos_docker_settings: "{{ docker_bridge_network_settings }}"
wallos_webui_port: 3015

wgeasy_docker_settings: "{{ docker_bridge_network_settings }}"
wireguard_mode: "server"
wgeasy_webui_port: 3016

#################################
# ansilbe-collection-smarthome  #
#################################

smarthome_docker_settings: "{{ docker_bridge_network_settings }}"
smarthome_user: "{{ system_user }}"

# TODO: with this variable being empty, zigbee2mqtt installation is ignored, making it not testable
smarthome_zigbee_coordinator: ""

homeassistant_port: 3017
