---
ansible_user: "runner_42"

system_user_name: "{{ ansible_user }}"
system_user_password: "test4242"
system_timezone: "Europe/Amsterdam"

system_user_uid: "4242"
system_user_gid: "4242"

#################################
# docker                        #
#################################

docker_bridge_network_settings:
  network: "docker-network-main"
  puid: "{{ system_user_uid }}"
  pgid: "{{ system_user_gid }}"
  tz: "{{ system_timezone }}"

docker_host_network_settings:
  network: "host"
  puid: "host"
  pgid: "{{ system_user_gid }}"
  tz: "{{ system_timezone }}"

# TODO: with this variable being "false", Watchtower installation is ignored, making it not testable
# The underlying role needs to be splitted
docker_autoupdate_enabled: false

#################################
# ansilbe-collection-yams       #
#################################

yams_docker_settings: "{{ docker_bridge_network_settings }}"
yams_user:
  name: "{{ system_user_name }}"
  password: "{{ system_user_password }}"

immich_port: 3001

jellyfin_port: 3002
jellyfin_jellyseerr_port: 3003

paperlessngx_port: 3004

prowlarr_port: 3005

radarr_port: 3006

sonarr_port: 3007

transmission_ui_port: 3008
transmission_whitelist:
  - "*.*.*.*"

#################################
# ansilbe-collection-selfhosted #
#################################

duplicati_docker_settings: "{{ docker_bridge_network_settings }}"
duplicati_port: 3009

filebrowser_docker_settings: "{{ docker_bridge_network_settings }}"
filebrowser_port: 3010

glances_docker_settings: "{{ docker_host_network_settings }}"
glances_webui_port: 61208

homebox_docker_settings: "{{ docker_bridge_network_settings }}"
homebox_webui_port: 3011

rss_docker_settings: "{{ docker_bridge_network_settings }}"
rss_miniflux_webui_port: 3012
rss_rssbridge_webui_port: 3013

vaultwarden_docker_settings: "{{ docker_bridge_network_settings }}"
vaultwarden_port: 3014

wallos_docker_settings: "{{ docker_bridge_network_settings }}"
wallos_webui_port: 3015

wgeasy_docker_settings: "{{ docker_bridge_network_settings }}"
wireguard_mode: "server"
wgeasy_webui_port: 3016

#################################
# ansilbe-collection-smarthome  #
#################################

smarthome_docker_settings: "{{ docker_bridge_network_settings }}"

# TODO: with this variable being empty, zigbee2mqtt installation is ignored, making it not testable
smarthome_zigbee_coordinator: ""

homeassistant_port: 3017
