---
# https://github.com/linuxserver/docker-freshrss#parameters

- ansible.builtin.set_fact:
    freshrss_service_id: "freshrss"
    freshrss_root_dir: "{{ docker_dir }}/freshrss"

- name: "Run app container"
  community.general.docker_container:
    name: "{{ freshrss_service_id }}"
    image: "lscr.io/linuxserver/freshrss:{{ newsfeed_freshrss_version }}"
    networks:
      - name: "{{ docker_network_name }}"
    state: "started"
    env:
      TZ: "{{ system_timezone }}"
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
    ports:
      - "{{ newsfeed_freshrss_port }}:80"
    volumes:
      - "{{ freshrss_root_dir }}:/config"
    restart_policy: "unless-stopped"
