---
- name: "Register users' UID and GID"
  ansible.builtin.include_role:
    name: "docker"
    tasks_from: "register-uid.yml"

- name: "Bootstrap media server"
  ansible.builtin.include_role:
    name: "artyorsh.yams.yams"
  vars:
    yams_user:
      name: "{{ system_user_name }}"
      password: "{{ system_user_password }}"

    yams_dir:
      downloads: "{{ storage_smb_share_local_dir }}/Downloads"
      photos: "{{ storage_smb_share_local_dir }}/Photos"
      movies: "{{ storage_smb_share_local_dir }}/Movies"
      tvshows: "{{ storage_smb_share_local_dir }}/TV"

    yams_docker_settings:
      network: "{{ docker_network_name }}"
      puid: "{{ docker_uid }}"
      pgid: "{{ docker_gid }}"
      tz: "{{ system_timezone }}"
