---
- name: "Create media network"
  community.general.docker_network:
    name: "{{ media_network_name }}"

- name: "Bootstrap media server"
  ansible.builtin.include_role:
    name: "artyorsh.yams.yams"
  vars:
    yams_user:
      name: "{{ system_user_name }}"
      password: "{{ system_user_password }}"

    yams_dir:
      downloads: "{{ storage_smb_share_local_dir }}/Downloads"
      photos: "{{ storage_smb_share_local_dir }}/Photos"
      movies: "{{ storage_smb_share_local_dir }}/Movies"
      tvshows: "{{ storage_smb_share_local_dir }}/TV"

    yams_docker_settings:
      network: "{{ media_network_name }}"
      puid: "{{ system_user_uid }}"
      pgid: "{{ system_user_gid }}"
      tz: "{{ system_timezone }}"
