---
- name: "Register users' UID and GID"
  ansible.builtin.include_role:
    name: "docker"
    tasks_from: "register-uid.yml"

- name: "Install Transmission"
  ansible.builtin.include_tasks: "transmission.yml"

- name: "Install Prowlarr"
  ansible.builtin.include_tasks: "prowlarr.yml"

- name: "Install Radarr"
  ansible.builtin.include_tasks: "radarr.yml"

- name: "Install Sonarr"
  ansible.builtin.include_tasks: "sonarr.yml"

- name: "Install Jellyfin"
  ansible.builtin.include_tasks: "jellyfin.yml"

- name: "Install Jellyseerr"
  ansible.builtin.include_tasks: "jellyseerr.yml"

- name: "Install Immich"
  ansible.builtin.include_tasks: "immich.yml"
