---
- name: "Ensure media directory exists"
  ansible.builtin.file:
    path: "{{ media_storage_dir }}"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0770

- name: "Create credentials file for network drive"
  ansible.builtin.template:
    src: "storage-credentials.j2"
    dest: "{{ media_storage_dir }}/.credentials"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0440

- name: "Mount external media storage"
  when: media_storage_network_location is defined
  ansible.posix.mount:
    boot: true
    src: "{{ media_storage_network_location }}"
    path: "{{ media_storage_dir }}"
    state: "mounted"
    fstype: "cifs"
    opts: "credentials={{ media_storage_dir }}/.credentials,uid={{ user_name }},gid={{ user_name }},x-systemd.automount"
