---
- name: "Ensure media directory exists"
  ansible.builtin.file:
    path: "{{ media_storage_dir }}"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0770

- name: "Mount external media storage"
  when: media_storage_network_location is defined
  ansible.posix.mount:
    boot: true
    src: "{{ media_storage_network_location }}"
    path: "{{ media_storage_dir }}"
    state: "mounted"
    fstype: "cifs"
    opts: "username={{ media_external_storage_user }},password={{ media_external_storage_password }},x-systemd.automount"
