---
- name: "Connect SMB Share"
  when: storage_smb_share_address is defined
  ansible.builtin.include_tasks: "smb.yml"

- name: "Install Filebrowser"
  ansible.builtin.include_tasks: "filebrowser.yml"
