---
- name: "Register users' UID and GID"
  ansible.builtin.include_role:
    name: "docker"
    tasks_from: "register-uid.yml"

- ansible.builtin.include_tasks: "smb.yml"
  when: smb_share_address is defined

- ansible.builtin.include_tasks: "filebrowser.yml"
