---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    docker_backup_script: "/etc/docker-backup.sh"

- name: "Template backup script"
  ansible.builtin.template:
    src: "docker-backup.sh.j2"
    dest: "{{ docker_backup_script }}"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_group }}"
    mode: "0740"

- name: "Create a backup cron"
  ansible.builtin.cron:
    name: "Backup docker containers"
    user: "{{ system_user_name }}"
    job: "{{ docker_backup_script }}"
    month: "{{ docker_backup_schedule.month | default('*') }}"
    weekday: "{{ docker_backup_schedule.weekday | default('0') }}"
    hour: "{{ docker_backup_schedule.hour | default('3') }}"
    minute: "{{ docker_backup_schedule.minute | default('0') }}"
