---
- name: Set amd64 arch
  set_fact:
    repo_arch: amd64
  when: ansible_architecture == "x86_64"

- name: Set arm64 arch
  set_fact:
    repo_arch: "{{ ansible_architecture }}"
  when: ansible_architecture == "arm64"

- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['distribution'] }}.yml"
- name: Install required system packages
  package:
    state: present
    name: "{{ docker_deps }}"

- name: Install Docker (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{ repo_arch }}] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_lsb['codename'] }} stable"
        state: present

- name: Update apt and install docker-ce
  block:
    - name: Attempt installation
      apt:
        update_cache: true
        name: "{{ docker_packages }}"
        state: present
  rescue:
    - name: Fix the dumb Ubuntu Jammy error
      replace:
        path: /etc/systemd/system/multi-user.target.wants/docker.service
        regexp: "fd://"
        replace: "unix://"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '>=')

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ user_name }}" to group docker
  user:
    name: "{{ user_name }}"
    groups:
      - docker
    append: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true

- name: Chmod the data folder
  become: true
  file:
    dest: "{{ docker_dir }}"
    state: directory
    owner: "{{ user_name }}"
    mode: "0775"
    group: "users"
    recurse: true

- name: Create the wg network
  docker_network:
    name: wg_network
