---
- name: "Install and configure Docker"
  ansible.builtin.include_role:
    name: "artyorsh.selfhosted.docker"
  vars:
    docker_autobackup_enabled: true
    docker_autobackup_dest_dir: "{{ storage_smb_share_local_dir }}/backups/docker-volumes"
    docker_autobackup_schedule: { weekday: "*", hour: 2 }
    # docker_autobackup_containers: []

    docker_autoprune_enabled: true
    docker_autoprune_schedule: { weekday: "*", hour: 1, minute: 30 }
    docker_autoprune_until_hours: 168

    docker_autoupdate_enabled: true
    docker_autoupdate_ignore_list: ["cloudflare", "wireguard"]
    docker_autoupdate_watchtower_docker_settings: "{{ docker_bridge_network_settings }}"

- name: "Create shared network"
  community.general.docker_network:
    name: "{{ docker_network_name }}"
