---
# https://github.com/geerlingguy/ansible-role-docker/issues/434#issuecomment-1815767476

- name: "Run geerlingguy.docker role"
  ansible.builtin.include_role:
    name: "geerlingguy.docker"

- name: "Create shared network"
  community.general.docker_network:
    name: "{{ docker_network_name }}"

- name: "Enable container backups"
  ansible.builtin.include_tasks: "container-backup.yml"
  when: docker_backup_enabled

- name: "Enable Watchtower"
  ansible.builtin.include_role:
    name: "artyorsh.selfhosted.watchtower"
  vars:
    watchtower_schedule: "0 0 3 * * 1" # 3AM every Monday
    watchtower_ignore_list:
      - "cloudflare"
      - "wireguard"
      - "filebrowser"
    watchtower_docker_settings: "{{ docker_default_settings }}"
