---
# https://github.com/geerlingguy/ansible-role-docker/issues/434#issuecomment-1815767476

- ansible.builtin.include_role:
    name: "geerlingguy.docker"

- name: "Create shared network"
  community.general.docker_network:
    name: "{{ docker_network_name }}"

- name: "Enable Watchtower"
  ansible.builtin.include_tasks: "watchtower.yml"
  when: docker_watchtower_enabled

- name: "Register users' UID and GID"
  ansible.builtin.include_tasks: "register-uid.yml"
