---
- name: "Install cloudflared"
  ansible.builtin.include_tasks: "cloudflared.yml"

- name: "Allow SSH via cloudflare tunnel"
  when: cloudflare_tunnel_ssh_enabled
  ansible.builtin.include_tasks: "cloudflared-ssh.yml"
