- name: "For client mode, assert that tunnel file exists"
  when: wg_client_mode_enabled
  block:
    - ansible.builtin.stat:
        path: "{{ wg_client_tunnel_file }}"
      register: wg_client_tunnel_file_stat

    - ansible.builtin.assert:
        that: wg_client_tunnel_file_stat.stat.exists
        fail_msg: |
          "Tunnel file does not exist at path {{ wg_client_tunnel_file }}"
          "Please check the wg_client_tunnel_file variable"