- name: "For client mode, assert that tunnel file exists"
  when: wireguard_client_mode_enabled
  block:
    - name: "Get tunnel file stats"
      ansible.builtin.stat:
        path: "{{ wireguard_client_tunnel_file }}"
      register: wg_client_tunnel_file_stat

    - name: "Assert tunnel file exists"
      ansible.builtin.assert:
        that: wg_client_tunnel_file_stat.stat.exists
        fail_msg: |
          "Tunnel file does not exist at path {{ wireguard_client_tunnel_file }}"
          "Please check the wireguard_client_tunnel_file variable"
