---
- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  loop:
    - "wireguard"
    - "openresolv"

- name: "Copy tunnel file"
  ansible.builtin.copy:
    src: "{{ wireguard_client_tunnel_file }}"
    dest: "/etc/wireguard/wg-client.conf"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_group }}"
    mode: "0400"

- name: "Make sure wireguard connection is established"
  block:
    - name: "Disconnect tunnel"
      ansible.builtin.command: "wg-quick down wg-client"
      failed_when: false
      changed_when: false

    - name: "Connect tunnel"
      ansible.builtin.command: "wg-quick up wg-client"
      changed_when: false

# TODO: https://www.ivpn.net/knowledgebase/linux/linux-autostart-wireguard-in-systemd/
- name: "Create an autostart cron"
  ansible.builtin.cron:
    name: "Turn on wireguard"
    user: "{{ system_user_name }}"
    special_time: "reboot"
    job: "sleep 10; wg-quick up wg-client"
